service: my-serverless-service-test-logs

provider:
  name: aws
  runtime: nodejs18.x
  stage: ${opt:stage, 'develop'}
  region: us-east-1
  logRetentionInDays: ${self:custom.logRetentionInDays.${self:provider.stage}}

custom:
  functionName: helloFunction # Definimos una variable personalizada llamada "functionName"
  logRetentionInDays:
    production: !Ref 'AWS::NoValue'
    develop: ${ssm:/develop2}
    uat: 5

functions:
  api:
    handler: index.handler
    events:
      - httpApi:
          path: /
          method: get
